CREATE TABLE macronutrient_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calories DOUBLE PRECISION NOT NULL,
    carbs DOUBLE PRECISION NOT NULL,
    proteins DOUBLE PRECISION NOT NULL,
    fats DOUBLE PRECISION NOT NULL
);

CREATE TABLE mealplan_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(12),
    CONSTRAINT uk_mealplan_type_name UNIQUE (name)
);

CREATE TABLE tracking_goal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    target_macros BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tracking_goal_target_macros FOREIGN KEY (target_macros) REFERENCES macronutrient_values (id)
);

CREATE TABLE tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_date DATE NOT NULL,
    user_id BIGINT NOT NULL,
    tracking_goal_id BIGINT NOT NULL,
    consumed_macros_id BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tracking_goal FOREIGN KEY (tracking_goal_id) REFERENCES tracking_goal (id),
    CONSTRAINT fk_tracking_consumed_macros FOREIGN KEY (consumed_macros_id) REFERENCES macronutrient_values (id)
);

CREATE TABLE tracking_meal_plan_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    mealplan_type BIGINT,
    day_number INTEGER,
    tracking_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tracking_meal_plan_entry_type FOREIGN KEY (mealplan_type) REFERENCES mealplan_type (id),
    CONSTRAINT fk_tracking_meal_plan_entry_tracking FOREIGN KEY (tracking_id) REFERENCES tracking (id)
);

CREATE TABLE water_intakes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount_ml INTEGER NOT NULL,
    intake_date DATE NOT NULL,
    registered_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
