CREATE TABLE IF NOT EXISTS macronutrient_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calories DOUBLE PRECISION NOT NULL,
    carbs DOUBLE PRECISION NOT NULL,
    proteins DOUBLE PRECISION NOT NULL,
    fats DOUBLE PRECISION NOT NULL
);

DO $$
DECLARE
    target_table TEXT;
    meal_type TEXT;
BEGIN
    IF to_regclass('public.mealplan_types') IS NOT NULL THEN
        target_table := 'mealplan_types';
    ELSE
        CREATE TABLE IF NOT EXISTS mealplan_type (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(12)
        );

        target_table := 'mealplan_type';
    END IF;

    FOREACH meal_type IN ARRAY ARRAY['BREAKFAST', 'LUNCH', 'DINNER', 'HEALTHY']
    LOOP
        EXECUTE format(
            'INSERT INTO %I (name)
             SELECT %L
             WHERE NOT EXISTS (SELECT 1 FROM %I WHERE name = %L)',
            target_table,
            meal_type,
            target_table,
            meal_type
        );
    END LOOP;
END $$;

INSERT INTO macronutrient_values (calories, carbs, proteins, fats)
SELECT 2000.0, 250.0, 125.0, 55.6
WHERE NOT EXISTS (
    SELECT 1 FROM macronutrient_values
    WHERE calories = 2000.0 AND carbs = 250.0 AND proteins = 125.0 AND fats = 55.6
);

INSERT INTO macronutrient_values (calories, carbs, proteins, fats)
SELECT 1500.0, 150.0, 131.25, 41.7
WHERE NOT EXISTS (
    SELECT 1 FROM macronutrient_values
    WHERE calories = 1500.0 AND carbs = 150.0 AND proteins = 131.25 AND fats = 41.7
);

INSERT INTO macronutrient_values (calories, carbs, proteins, fats)
SELECT 2500.0, 343.75, 156.25, 55.6
WHERE NOT EXISTS (
    SELECT 1 FROM macronutrient_values
    WHERE calories = 2500.0 AND carbs = 343.75 AND proteins = 156.25 AND fats = 55.6
);

INSERT INTO macronutrient_values (calories, carbs, proteins, fats)
SELECT 1800.0, 22.5, 112.5, 140.0
WHERE NOT EXISTS (
    SELECT 1 FROM macronutrient_values
    WHERE calories = 1800.0 AND carbs = 22.5 AND proteins = 112.5 AND fats = 140.0
);
