name: CI

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  java-ci:
    name: Compile Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout service repository
        uses: actions/checkout@v4

      - name: Setup Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"
          cache: maven

      - name: Build
        run: mvn clean package
